<?php

namespace Theaterjobs\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use Theaterjobs\MembershipBundle\Model\ProfileInterface;

/**
 * BillingAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingAddressRepository extends EntityRepository {

    public function findOneByProfile(ProfileInterface $profile) {
        $qb = $this->createQueryBuilder("b");
        $qb->innerJoin(
                'b.profile', 'p', Expr\Join::WITH, $qb->expr()->eq('p.id', ':profile_id')
        )->setParameter("profile_id", $profile->getId());

        return $qb->getQuery()->getOneOrNullResult();
    }

}
