<?php

namespace Theaterjobs\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryTaxRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryTaxRateRepository extends EntityRepository
{

}
