<?php

namespace Theaterjobs\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DebitAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebitAccountRepository extends EntityRepository
{
    public function debitAccountByProfile($profile){
        $qb = $this->createQueryBuilder('debit');
        $debit = $qb->select('debit')
            ->where('debit.profile= :profile')
                ->setParameter('profile', $profile)
                ->getQuery()
                ->getResult();
        return $debit;
    }
}
