<?php

namespace Theaterjobs\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Repository for the IbanBlacklist.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IbanBlacklistRepository extends EntityRepository
{
    public function countBlacklisted($value)
    {
        $qb = $this->createQueryBuilder('i');
        $result = $qb->select('count(i.id)')
            ->where('i.iban= :val')
            ->setParameter('val', $value)
            ->getQuery()
            ->getSingleScalarResult();

        return $result ? $result : null;
    }

}
