doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                server_version: 5.5
            user_pool:
                driver:   "%database_driver%"
                host:     '%old_database_host%'
                port:     '%database_port%'
                dbname:   '%old_database_name%'
                user:     '%old_database_user%'
                password: '%old_database_password%'
                charset:  UTF8
                # @todo not sure if its the right db server version Jana needs to check this
                server_version: 5.5

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                query_cache_driver: memcache
                result_cache_driver:
                  type: memcache
                  host: localhost
                  port: 11211
                  instance_class: Memcache
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
            user_pool:
                connection: user_pool
        resolve_target_entities:
            Theaterjobs\MainBundle\Model\UserInterface: Theaterjobs\UserBundle\Entity\User
            Theaterjobs\InserateBundle\Model\UserInterface: Theaterjobs\UserBundle\Entity\User
            Theaterjobs\InserateBundle\Model\CategoryInterface: Theaterjobs\CategoryBundle\Entity\Category
            Theaterjobs\InserateBundle\Model\AddressInterface: Theaterjobs\MainBundle\Entity\Address
            Theaterjobs\InserateBundle\Model\QualificationInterface: Theaterjobs\ProfileBundle\Entity\Qualification
            Theaterjobs\InserateBundle\Model\ProfileInterface: Theaterjobs\ProfileBundle\Entity\Profile
            Theaterjobs\InserateBundle\Model\UserOrganizationInterface: Theaterjobs\UserBundle\Entity\UserOrganization
            Theaterjobs\MembershipBundle\Model\UserInterface: Theaterjobs\UserBundle\Entity\User
            Theaterjobs\MembershipBundle\Model\ProfileInterface: Theaterjobs\ProfileBundle\Entity\Profile
            Theaterjobs\ProfileBundle\Model\UserInterface: Theaterjobs\UserBundle\Entity\User
            Theaterjobs\ProfileBundle\Model\CategoryInterface: Theaterjobs\CategoryBundle\Entity\Category
            Theaterjobs\ProfileBundle\Model\BillingAddressInterface: Theaterjobs\MembershipBundle\Entity\BillingAddress
            Theaterjobs\ProfileBundle\Model\DebitAccountInterface: Theaterjobs\MembershipBundle\Entity\DebitAccount
            Theaterjobs\ProfileBundle\Model\SepaMandateInterface: Theaterjobs\MembershipBundle\Entity\SepaMandate
            Theaterjobs\ProfileBundle\Model\PaymentmethodInterface: Theaterjobs\MembershipBundle\Entity\Paymentmethod
            Theaterjobs\ProfileBundle\Model\BookingInterface: Theaterjobs\MembershipBundle\Entity\Booking
            Theaterjobs\ProfileBundle\Model\InserateInterface: Theaterjobs\InserateBundle\Entity\Inserate
            Theaterjobs\ProfileBundle\Model\JobInterface: Theaterjobs\InserateBundle\Entity\Job
            Theaterjobs\ProfileBundle\Model\OrganizationInterface: Theaterjobs\InserateBundle\Entity\Organization
            Theaterjobs\UserBundle\Model\ProfileInterface: Theaterjobs\ProfileBundle\Entity\Profile
            Theaterjobs\UserBundle\Model\OrganizationInterface: Theaterjobs\InserateBundle\Entity\Organization
            Theaterjobs\StatsBundle\Model\UserInterface: Theaterjobs\UserBundle\Entity\User
            Theaterjobs\NewsBundle\Model\OrganizationInterface: Theaterjobs\InserateBundle\Entity\Organization
            Theaterjobs\NewsBundle\Model\ProfileInterface: Theaterjobs\ProfileBundle\Entity\Profile
            Theaterjobs\ForumBundle\Model\OrganizationInterface: Theaterjobs\InserateBundle\Entity\Organization
