<?php

namespace Theaterjobs\InserateBundle\Entity;

/**
 * ApplicationRejectDraftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRejectDraftRepository extends \Doctrine\ORM\EntityRepository
{
}
