<?php

namespace Theaterjobs\InserateBundle\Entity;

use Theaterjobs\ProfileBundle\Entity\Profile;

/**
 * ApplicationTrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationTrackRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Profile $profile
     * @param Inserate $job
     * @return array
     */
    public function findIdenticalApplication(Profile $profile , Inserate $job) {
        $qb = $this->_em->createQueryBuilder()
            ->select('a')
            ->from('TheaterjobsInserateBundle:ApplicationTrack', 'a')
            ->where('a.profile = :profile ')
            ->andwhere("a.job = :job")
            ->orderBy('a.createdAt', 'DESC')
            ->setParameters(array('profile' => $profile->getId(), 'job' => $job->getId()));
        return $qb->getQuery()->getOneOrNullResult();
    }

}
