<?php

namespace Theaterjobs\InserateBundle\Entity;

/**
 * EducationKindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationKindRepository extends \Doctrine\ORM\EntityRepository
{
}
