<?php

namespace Theaterjobs\InserateBundle\Entity;

/**
 * JobmailQuery
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobmailQueryRepository extends \Doctrine\ORM\EntityRepository
{
}
