<?php

namespace Theaterjobs\InserateBundle\Entity;

use Theaterjobs\UserBundle\Entity\User;

/**
 * JobMailRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobmailRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser(User $user)
    {
        return $this
            ->getEntityManager()
            ->createQuery(
                'SELECT j FROM TheaterjobsInserateBundle:Jobmail j WHERE j.user = :id'
            )
            ->setParameter('id', $user->getId())
            ->getResult()
        ;
    }
}
