<?php

namespace Theaterjobs\InserateBundle\Entity;

/**
 * JobTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobTitleRepository extends \Doctrine\ORM\EntityRepository
{
    public function titleSuggest($word)
    {
        $qb = $this->createQueryBuilder('jobTitle');

        $tags = $qb->select('jobTitle')
            ->where('jobTitle.title LIKE :word')
            ->setParameter('word', '%' . $word . '%')
            ->getQuery()->getResult();
        return $tags;
    }
}
