<?php

namespace Theaterjobs\InserateBundle\Entity;

/**
 * OrganizationStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationStageRepository extends \Doctrine\ORM\EntityRepository
{
}
