<?php

namespace Theaterjobs\InserateBundle\Entity;

/**
 * OrganizationEnsembleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationStaffRepository extends \Doctrine\ORM\EntityRepository
{
}
