<?php

namespace Theaterjobs\InserateBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Carbon\Carbon;
use Theaterjobs\AdminBundle\Model\StageTagSearch;

/**
 * EventMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends EntityRepository
{

    /**
     * @param string $title
     * @return \Doctrine\ORM\Query
     */
    public function tagSuggest($title)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where('t.title LIKE :title')
            ->andWhere('t.checked = 1')
            ->orderBy('t.title', 'ASC')
            ->setParameter('title', sprintf('%%%s%%', $title));

        return $qb->getQuery();
    }

    /**
     * @param StageTagSearch $stageTagSearch
     * @return \Doctrine\ORM\Query
     */
    public function adminListSearch(StageTagSearch $stageTagSearch)
    {
        $qb = $this->createQueryBuilder('t');

        if ($stageTagSearch->getTitle()) {
            $qb
                ->where($qb->expr()->like('t.title', ':title'))
                ->setParameter('title', sprintf('%%%s%%', $stageTagSearch->getTitle()));
        }

        if (is_numeric($stageTagSearch->getChoices())) {
            $qb
                ->andWhere($qb->expr()->eq('t.checked', ':checked'))
                ->setParameter('checked', $stageTagSearch->getChoices());
        }

        if ($stageTagSearch->getOrderCol()) {
            $qb->orderBy(sprintf("t.%s", $stageTagSearch->getOrderCol()), $stageTagSearch->getOrder());
        }

        return $qb->getQuery();
    }
}
