parameters:
  theaterjobs_user.registration.listener.class: Theaterjobs\UserBundle\EventListener\RegistrationListener
  theaterjobs_user.form.registration.class: Theaterjobs\UserBundle\Form\Type\RegistrationFormType
  theaterjobs_user.form.resetting.class: Theaterjobs\UserBundle\Form\Type\ResettingFormType
  theaterjobs_user.component.authentication.handler.logout.success.class: Theaterjobs\UserBundle\Component\Authentication\Handler\LogoutSuccessHandler
  theaterjobs_user.security.logout_handler.class: Theaterjobs\UserBundle\Security\LogoutHandler
  theaterjobs_user.locale_listener.class: Theaterjobs\UserBundle\EventListener\LocaleListener
  theaterjobs_user.event_listener.password.resetting.class: Theaterjobs\UserBundle\EventListener\PasswordResettingListener
services:
# EXAMPLE
#    app.mailer:
#        class:     AppBundle\Mailer
#        arguments: ['%app.mailer.transport%']
  kernel.listener.your_listener_name:
    class: Theaterjobs\UserBundle\EventListener\LoginListener
    arguments:
      - '@service_container'
    tags:
      - {name: 'kernel.event_listener', event: 'security.interactive_login', method: 'onSecurityInteractiveLogin', priority: 100}
  theaterjobs_user.registration.listener:
    class: '%theaterjobs_user.registration.listener.class%'
    arguments:
      - '@service_container'
    tags:
      - {name: 'kernel.event_subscriber'}
  theaterjobs_user.form.registration:
    class: '%theaterjobs_user.form.registration.class%'
    arguments:
      - '%fos_user.model.user.class%'
    tags:
      - {name: 'form.type', alias: 'theaterjobs_user_registration'}
  theaterjobs_user.form.resetting:
    class: '%theaterjobs_user.form.resetting.class%'
    arguments:
      - '%fos_user.model.user.class%'
    tags:
      - {name: 'form.type', alias: 'theaterjobs_user_resetting'}
  theaterjobs_user.component.authentication.handler.logout.success:
    class: '%theaterjobs_user.component.authentication.handler.logout.success.class%'
    arguments:
      - '@router'
      - '@doctrine.orm.entity_manager'
      - '@fos_user.user_manager'
    tags:
      - {name: 'monolog.logger', channel: 'security'}
  theaterjobs_user.security.logout_handler:
    class: '%theaterjobs_user.security.logout_handler.class%'
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - {name: 'monolog.logger'}
  theaterjobs_user.locale_listener:
    class: '%theaterjobs_user.locale_listener.class%'
    arguments:
      - '%locale%'
    tags:
      - {name: 'kernel.event_subscriber'}
  theaterjobs_user.event_listener.password.resetting:
    class: '%theaterjobs_user.event_listener.password.resetting.class%'
    arguments:
      - '@router'
    tags:
      - {name: 'kernel.event_subscriber'}
