<?php

namespace Theaterjobs\ProfileBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Theaterjobs\AdminBundle\Model\CreatorSearch;

/**
 * CreatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreatorRepository extends NestedTreeRepository
{
    public function getCheckedCreators()
    {
        $qb = $this->createQueryBuilder('creator');
        $qb->where($qb->expr()->eq('creator.checked', ':param'));
        $qb->andWhere($qb->expr()->isNull('creator.parent'));
        $qb->setParameter(':param', true);
        $qb->orderBy('creator.name', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function getMergedCreators()
    {
        $qb = $this->createQueryBuilder('creator');
        $qb->where($qb->expr()->isNotNull('creator.parent'));
        $qb->orderBy('creator.name', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function getUnCheckedCreators()
    {
        $qb = $this->createQueryBuilder('creator');
        $qb->where($qb->expr()->eq('creator.checked', ':param'));
        $qb->andWhere($qb->expr()->isNull('creator.parent'));
        $qb->setParameter(':param', false);
        $qb->orderBy('creator.id', 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function creatorAutosuggestion($name)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->addSelect("(CASE WHEN c.name like  '" . $name . "%'   THEN 1  WHEN c.name like '%" . $name . "'  THEN 2 ELSE 3 END) AS HIDDEN ordCol")
            ->where('c.name LIKE :name ')
            ->andWhere($qb->expr()->eq('c.checked', ':checked'))
            ->setParameter('name', '%' . $name . '%')
            ->setParameter('checked', true)
            ->orderBy("ordCol");

        return $qb->getQuery();
    }

    public function mergeCreatorQueryBuilder(Creator $creator)
    {

        $qb = $this->createQueryBuilder('creator');
        $qb->andWhere($qb->expr()->eq('creator.checked', ':param'));
        $qb->andWhere($qb->expr()->neq('creator.id', $creator->getId()));
        $qb->setParameter(':param', true)
            ->orderBy('creator.name', 'ASC');

        return $qb;
    }

    public function getSiblingsByRoot($root)
    {
        $qb = $this->createQueryBuilder('node');
        $qb->orderBy('node.root, node.lft', 'ASC')
            ->where($qb->expr()->eq('node.root', ':root'))
            ->setParameter('root', $root)
            ->getQuery();

        return $qb->getQuery()->getResult();
    }

    public function adminListSearch(CreatorSearch $adminCreatorSearch)
    {
        $qb = $this->createQueryBuilder('c');

        if ($adminCreatorSearch->getName()) {
            $qb
                ->where($qb->expr()->like('c.name', ':name'))
                ->setParameter('name', sprintf('%%%s%%', $adminCreatorSearch->getName()));
        }

        if (is_numeric($adminCreatorSearch->getPublished())) {
            $qb
                ->andWhere($qb->expr()->eq('c.checked', ':checked'))
                ->setParameter('checked', $adminCreatorSearch->getPublished());
        }

        if ($adminCreatorSearch->getOrderCol()) {
            $qb->orderBy(sprintf("c.%s", $adminCreatorSearch->getOrderCol()), $adminCreatorSearch->getOrder());
        }

        return $qb->getQuery();
    }

    /**
     * @param $creatorId
     * @return mixed
     */
    public function getCreatorProductionIds($creatorId)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->leftJoin('c.productions', 'p')
            ->select('p.id as id')
            ->where('c.id = :id')
            ->setParameter('id', $creatorId);

        $result = $qb->getQuery()->getArrayResult();

        return array_reduce($result, function ($acc, $item) {
            if ($item['id'] != null) {
                $acc[] = $item['id'];
            }
            return $acc;
        }, []);
    }
}
