<?php
namespace Theaterjobs\ProfileBundle\Entity;
/**
 * OldEducationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OldEducationRepository extends \Doctrine\ORM\EntityRepository
{
}