<?php

namespace Theaterjobs\ProfileBundle\Entity;

/**
 * OldExtrasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OldExtrasRepository extends \Doctrine\ORM\EntityRepository
{
}
