<?php

namespace Theaterjobs\ProfileBundle\Entity;

/**
 * PersonalDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalDataRepository extends \Doctrine\ORM\EntityRepository
{
}
