<?php

namespace Theaterjobs\ProfileBundle\Entity;

/**
 * ProductionParticipationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionParticipationsRepository extends \Doctrine\ORM\EntityRepository
{
}
