<?php

namespace Theaterjobs\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use Theaterjobs\ProfileBundle\Model\CategoryInterface;

/**
 * TypeOfCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfCategoryRepository extends EntityRepository {

    public function findByCategory(CategoryInterface $category) {
        $qb = $this->createQueryBuilder("t");
        $qb->innerJoin(
                't.categories', 'c', Expr\Join::WITH, $qb->expr()->eq('c.id', ':cat_id')
        )->setParameter('cat_id', $category->getId());

        return $qb->getQuery()->getResult();
    }

}
