<?php

namespace Theaterjobs\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Theaterjobs\AdminBundle\Model\JobHuntSearch;

/**
 * JobHuntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobHuntRepository extends EntityRepository
{
    /**
     * Search by name
     * @param $name
     * @return \Doctrine\ORM\Query
     */
    public function getJobHunts($name)
    {
        $qb = $this->createQueryBuilder('jh');
        if ($name) {
            $qb->where('jh.name like :name')
                ->setParameter('name', $name);
        }
        return $qb->getQuery();
    }

    /**
     * Search by name
     * @param $name
     * @return \Doctrine\ORM\Query
     */
    public function getNrJobHunts($name)
    {
        $qb = $this->createQueryBuilder('jh');
        $qb->select('count(jh.id) as total');
        if ($name) {
            $qb->where('jh.name like :name')
                ->setParameter('name', $name);
        }
        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * @param JobHuntSearch $jobHuntSearch
     * @return \Doctrine\ORM\Query
     */
    public function adminListSearch(JobHuntSearch $jobHuntSearch)
    {
        $qb = $this->createQueryBuilder('jh');

        if ($jobHuntSearch->getName()) {
            $qb
                ->where($qb->expr()->like('jh.name', ':name'))
                ->setParameter('name', sprintf('%%%s%%', $jobHuntSearch->getName()));
        }

        if ($jobHuntSearch->getOrderCol()) {
            $qb->orderBy(sprintf("jh.%s", $jobHuntSearch->getOrderCol()), $jobHuntSearch->getOrder());
        }

        return $qb->getQuery();
    }
}