<?php

namespace Theaterjobs\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Theaterjobs\AdminBundle\Model\NameChangeRequestSearch;

/**
 * NameChangeRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NameChangeRequestRepository extends EntityRepository
{
    public function getRequests($status)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $requests = $qb->select('nc')
            ->from('TheaterjobsUserBundle:NameChangeRequest', 'nc')
            ->where($qb->expr()->eq('nc.status', ':status'))
            ->setParameter('status', $status)
            ->getQuery()->getResult();
        return $requests;
    }

    public function adminListSearch(NameChangeRequestSearch $adminNameChangeRequestSearch)
    {
        $qb = $this->createQueryBuilder('nc');
        $qb->innerJoin('nc.createdBy', 'u');
        $qb->innerJoin('u.profile', 'p');
        $requests = $qb->select(
            'nc.id as id,
                    CONCAT(nc.oldFirstName, \' \', nc.oldLastName) as oldName,
                    CONCAT(nc.newFirstName, \' \', nc.newLastName) as newName,
                    nc.createdAt as createdAt,
                    p.slug as slug,
                    u.email as email')
            ->where('nc.status = :status')
            ->setParameter('status', $adminNameChangeRequestSearch->getChoices());


        return $requests->getQuery();
    }

    public function countRequests()
    {
        $qb = $this->createQueryBuilder('nc');

        $qb->select('nc.status,COUNT(nc.id) as total')
            ->groupBy('nc.status');

        return $qb->getQuery()->getScalarResult();
    }

}
