<?php

namespace Theaterjobs\AdminBundle\Entity;

use Theaterjobs\AdminBundle\Model\SepaXmlSearch;

/**
 * SepaXmlBillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SepaXmlBillingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get query of all sepa records
     * @param SepaXmlSearch $adminSepaXmlSearch
     * @return \Doctrine\ORM\Query
     */
    public function getSepaXml(SepaXmlSearch $adminSepaXmlSearch)
    {
        $qb = $this->createQueryBuilder('sx');
        $qb->leftJoin('sx.lastDownloadedBy', 'u')
            ->leftJoin('u.profile', 'p')
            ->select('sx.id as id,
                    sx.fileName as fileName,
                    CONCAT(p.firstName, \' \', p.lastName) as user,
                    p.slug as profileSlug,
                    sx.lastDownloadedAt as lastDownloadedAt'
        );

        if ($adminSepaXmlSearch->getOrderCol()) {
            $qb->orderBy(sprintf("%s", $adminSepaXmlSearch->getOrderCol()), $adminSepaXmlSearch->getOrder());
        }

        return $qb->getQuery();
    }

    /**
     * Get nr of all sepa records
     */
    public function getNrSepaXml()
    {
        $qb = $this->createQueryBuilder('sx');
        $qb->select('count(sx.id) as total');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
