<?php

namespace Theaterjobs\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Theaterjobs\InserateBundle\Entity\Job;
use \Doctrine\ORM\Query\Expr;

/**
 * SaveSearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaveSearchRepository extends EntityRepository
{
    /**
     * @param $id
     * @return []
     */
    public function searchesByPeopleId($id)
    {
        $qb = $this->createQueryBuilder('ss');
        $query = $qb->innerJoin('ss.profile', 'p', Expr\Join::WITH, 'p.id = :profId')
            ->orderBy('ss.createdAt', 'desc')
            ->setParameter('profId', $id);
        return $query->getQuery()->getResult();
    }

    /**
     * Get cron jobs of type job
     */
    public function getCronJobs()
    {
        $qb = $this->createQueryBuilder('ss');
        $query = $qb->select('ss.id')
            ->where('ss.notification = 1')
            ->andWhere('ss.entity = :entity')
            ->setParameter('entity', Job::class)
            ->getQuery();
        return $query->getResult();
    }
}
