<?php

namespace Theaterjobs\UserBundle\Entity;

/**
 * AdminUserCommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUserCommentsRepository extends \Doctrine\ORM\EntityRepository
{
}
