<?php

namespace Theaterjobs\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailBlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailBlacklistRepository extends EntityRepository
{

    public function checkForBannedEmail($email)
    {
        $qb = $this->createQueryBuilder('e');
        $banedEmails = $qb->select('e')
            ->where($qb->expr()->eq('e.email', ':email'))
            ->setParameter('email', $email)
            ->getQuery()
            ->getResult();

        return $banedEmails;

    }

}
