<?php

namespace Theaterjobs\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActivityRepository extends EntityRepository
{

    public function findUserOrgaActivity($user, $orga, $qb)
    {
        $class = addslashes(get_class($orga));
        $activity = $qb->select('activity')
            ->from('TheaterjobsUserBundle:UserActivity', 'activity')
            ->where('activity.entityId= :news_id')
            ->andWhere('activity.entityClass LIKE :class')
            ->andWhere('activity.user = :user')
            ->setParameters(array('news_id' => $orga->getId(), 'class' => '%' . $class, 'user' => $user))
            ->orderBy('activity.createdAt', 'DESC')
            ->getQuery()->getResult();

        return $activity;
    }

    public function getSingleLog($id)
    {
        $qb = $this->createQueryBuilder('ou');

        $qb->where('ou.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
}
