<?php

namespace Theaterjobs\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Carbon\Carbon;

/**
 * EventMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends EntityRepository
{

    public function tagSuggest($word)
    {

        $qb = $this->createQueryBuilder('tags');
        $qb
            ->where('tags.title LIKE :word')
            ->orderBy('tags.title', 'ASC')
            ->setParameter('word', '%' . $word . '%');

        return $qb->getQuery();
    }
}
